### PR TITLE
[Tinywl] Copy and adapt comments from wlroots code

### PR DESCRIPTION
**Pull request by lisael**
I also modified Server.viewAt method, so that the result view is
optional. This mimics with wlroots/tinywl/tinywl.c behaviour.

### CODE REVIEW

**Comment by ifreund** [comment]
> I also modified Server.viewAt method, so that the result view is
> optional. This mimics with wlroots/tinywl/tinywl.c behaviour.

the result of `viewAt()` is already optional: `?ViewAtResult`.

**Comment by lisael** [comment]
I wasn't clear in the commit message. The modification in question is https://github.com/swaywm/zig-wlroots/pull/44/files#diff-1a9e5a23677f92f1216d3ab36b81b28c04e30bdd4aa94d422c8086551220e743R224 and https://github.com/swaywm/zig-wlroots/pull/44/files#diff-1a9e5a23677f92f1216d3ab36b81b28c04e30bdd4aa94d422c8086551220e743R253 

For some reason (unclear to me, tbh) tinywl.c allows `NULL` in `view` and a non-null surface. This code: https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/tinywl/tinywl.c#L342 sets the surface and may retrurn `NULL` (equivalend to `ViewAtResult.view in the zig port) if the while condition `node != NULL` is false. I'm not sure it can happen.

That said, this change is a creeping logic change in a documentation PR. bad. If' you're OK with the comments, I remove this chunk.

**Comment by ifreund** [comment]
I haven't looked a the comments yet, the zig code is correct as is though and pointless complication won't be merged. I don't care if the code diverges from the C tinywl implementation, the point is to implement the same feature set in idiomatic Zig.

**Comment by lisael** [comment]
Right, I'll amend this PR without the logic changes.

**Comment by ifreund** [comment]
closing as stale, feel free to reopen/open a new one if you intend to continue.

**Pull request closed without merging**
