### PR TITLE
Add test

### PR DESCRIPTION
**Pull request by novakne**
Let me know what you think, I didn't use your `ref-decls` branch since it was old and I didn't really want to rebase it but it based on it

It's not perfect but it at least catch some typo for like `use of undeclared identifier` or `has no member called ...`

### CODE REVIEW

**Comment by novakne** [comment]
rebase for the `icccm` fix, and improve the test function, it catched more errors so I guess it's better

**Comment by novakne** [comment]
I guess we could also add at the end of each binding something like:
```zig
test "Seat" {
    comptime {
        @import("std").testing.refAllDecls(@This());
    }
}
```
Not sure if it would be better

**Review by ifreund — APPROVED** [review]
LGTM, thanks for working on this. I just cleaned up/expanded the commit messages a bit before merge.

**Comment by novakne** [comment]
No problem, you could delete the `ref-decls` branch, and I'll rebase the other PR to run the test

**Comment by ifreund** [comment]
> No problem, you could delete the `ref-decls` branch, and I'll rebase the other PR to run the test

thanks for the reminder, done!

**Pull request merged**
